### PR TITLE
[DEV-655] fixed bug with comparing versions, added local dev script

### PR DESCRIPTION
**Pull request by estokes-vs**
Will cut release for version 1.1 as it's a bugfix + comment formatting

### CODE REVIEW

**Comment by estokes-vs** [comment]
Version mismatch detected: 
       
  
    "terraform-ci": "v3"
  ,
  
    "terraform-ci-2": "v3"

**Comment by estokes-vs** [comment]
Newer Workflow Version Available: 
       
  
    "terraform-ci": "v3"
  ,
  
    "terraform-ci-2": "v3"

**Comment by estokes-vs** [comment]
Newer Workflow Version Available: 
       [
  
    "terraform-ci": "v3"
  ,
  
    "terraform-ci-2": "v3"
  
]

**Comment by estokes-vs** [comment]
Newer Workflow Version Available: 
       [
  
    "terraform-ci": "v3"
  ,
  
    "terraform-ci-2": "v3"
  
]

**Comment by estokes-vs** [comment]
Newer Workflow Version Available: 
       
  
    "terraform-ci": "v3"
  ,
  
    "terraform-ci-2": "v3"

**Comment by estokes-vs** [comment]
Newer Workflow Version Available: 
       undefined
  undefined
    "terraform-ci": "v3"
  undefined,
  undefined
    "terraform-ci-2": "v3"
  undefined
undefined

**Comment by estokes-vs** [comment]
Newer Workflow Version Available: 
         
    "terraform-ci": "v3"
  ,
  
    "terraform-ci-2": "v3"

**Comment by estokes-vs** [comment]
Newer Workflow Version Available: 
     {
  "terraform-ci": [
    "latest_major_release: v3, current_version: v1"
  ],
  "terraform-ci-2": [
    "latest_major_release: v3, current_version: v1"
  ]
}

**Comment by estokes-vs** [comment]
Newer Workflow Version Available: 
     ```
    {
  "terraform-ci": [
    "latest_major_release: v3, current_version: v1"
  ],
  "terraform-ci-2": [
    "latest_major_release: v3, current_version: v1"
  ]
}
    ```

**Comment by estokes-vs** [comment]
Newer Workflow Version Available: 
 ```
{
  "terraform-ci": [
    "latest_major_release: v3, current_version: v1"
  ],
  "terraform-ci-2": [
    "latest_major_release: v3, current_version: v1"
  ]
}
```

**Comment by estokes-vs** [comment]
Newer Workflow Version Available: 
 ```
{}
```

**Comment by estokes-vs** [comment]
Newer Workflow Version Available: 
 ```
{}
```

**Comment by estokes-vs** [comment]
Newer Workflow Version Available: 
 ```
{
  "terraform-ci": [
    "latest_major_release: v3, current_version: v1"
  ],
  "terraform-ci-2": [
    "latest_major_release: v3, current_version: v1"
  ]
}
```

**Comment by estokes-vs** [comment]
Newer Workflow Version Available: 
 ```
{
  "terraform-ci": [
    "latest_major_release: v3, current_version: v1"
  ],
  "terraform-ci-2": [
    "latest_major_release: v3, current_version: v1"
  ]
}
```

**Review by twmartin — APPROVED** [review]
Something that may be worth considering is de-duplicating with https://github.com/actions/github-script#run-a-separate-file. It would take some finagling to arrive at a script that would support both local and GHA execution, but it may be worth it.

**Pull request merged**
